---
# Nginx Installation and Configuration

- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: [nginx, install]

- name: Start and enable Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: [nginx, service]

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: [nginx, config]

- name: Create Nginx configuration for TechAcademy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    mode: '0644'
  tags: [nginx, config]

- name: Enable TechAcademy site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  tags: [nginx, config]

- name: Create Nginx main configuration
  template:
    src: nginx_main.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    backup: yes
  tags: [nginx, config]

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  tags: [nginx, config]

- name: Reload Nginx if configuration is valid
  systemd:
    name: nginx
    state: reloaded
  when: nginx_test.rc == 0
  tags: [nginx, service]

- name: Create SSL certificate directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0700'
  tags: [nginx, ssl]

- name: Create log directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/log/nginx
    - /var/log/{{ app_name }}
  tags: [nginx, logging]

